// Damage meter (Skada-style). Pure logic, no DOM: record every hit/heal/absorb during a fight, then drill down
//   level 1: per actor (bars)  →  level 2: per source on that actor (weapon, skill, dot, proc, legendary…)  →  level 3: every hit.
// Modes: damage done · healing done · damage taken · deaths/overkill. Works for any game: feed it plain records.
//
//   const m = new Meter(); m.startFight('goblin_patrol');
//   m.record({ t: 1.2, source: 'brannoc', sourceName: 'Brannoc', target: 'goblin_1', targetName: 'Goblin', kind: 'damage',
//              amount: 23, overkill: 4, crit: true, dtype: 'physical', via: 'skill:cleave', viaName: 'Cleave', tags: ['blocked'] });
//   m.endFight(); m.report('damage')  → [{ id, name, total, dps, hits, crits, sources: [...] }]
export const KINDS = ['damage', 'heal', 'absorb', 'taken'];
export class Meter {
  constructor({ maxFights = 50 } = {}) { this.fights = []; this.current = null; this.maxFights = maxFights; this.itemStats = {}; }
  startFight(label = 'fight', meta = {}) { this.current = { id: 'f' + (this.fights.length + 1), label, meta, start: null, end: null, records: [], actors: {} }; this.fights.push(this.current); if (this.fights.length > this.maxFights) this.fights.shift(); return this.current; }
  endFight() { if (this.current) { this.current.end = this.current.records.length ? Math.max(...this.current.records.map(r => r.t)) : 0; if (this.current.start == null) this.current.start = 0; } const f = this.current; this.current = null; return f; }
  /** r: { t (seconds or round), source, sourceName, target, targetName, kind ('damage'|'heal'|'absorb'), amount, overkill, crit, dtype, via, viaName, itemId, tags } */
  record(r) { if (!this.current) this.startFight(); const f = this.current; if (f.start == null) f.start = r.t ?? 0; const rec = { overkill: 0, crit: false, dtype: 'physical', via: 'attack', viaName: 'Attack', tags: [], ...r, amount: Math.max(0, Math.round(r.amount || 0)) }; f.records.push(rec); if (rec.source) f.actors[rec.source] = rec.sourceName || rec.source; if (rec.target) f.actors[rec.target] = rec.targetName || rec.target; if (rec.itemId && rec.kind === 'damage') { const s = this.itemStats[rec.itemId] ||= { itemId: rec.itemId, name: rec.viaName, damage: 0, hits: 0, kills: 0, crits: 0 }; s.damage += rec.amount; s.hits++; if (rec.crit) s.crits++; if (rec.killingBlow) s.kills++; } return rec; }
  kill(itemId) { if (itemId) { const s = this.itemStats[itemId] ||= { itemId, damage: 0, hits: 0, kills: 0, crits: 0 }; s.kills++; } }
  fight(id = null) { return id ? this.fights.find(f => f.id === id) : (this.current || this.fights[this.fights.length - 1]); }
  duration(f) { return Math.max(1, (f.end ?? (f.records.length ? Math.max(...f.records.map(r => r.t)) : 1)) - (f.start ?? 0)); }
  /** Records for a scope: one fight, or all fights merged ('all'). */
  records(scope = 'current') { if (scope === 'all') return this.fights.flatMap(f => f.records); const f = scope === 'current' ? this.fight() : this.fight(scope); return f ? f.records : []; }
  /** Level 1: per actor. mode: damage | heal | taken | absorb. */
  report(mode = 'damage', scope = 'current', { filterSide = null } = {}) {
    const recs = this.records(scope).filter(r => mode === 'taken' ? r.kind === 'damage' : r.kind === mode); const dur = scope === 'all' ? this.fights.reduce((s, f) => s + this.duration(f), 0) : this.duration(this.fight(scope === 'current' ? null : scope) || { records: [] });
    const by = {}; for (const r of recs) { const key = mode === 'taken' ? r.target : r.source; if (!key) continue; const name = mode === 'taken' ? r.targetName : r.sourceName; const a = by[key] ||= { id: key, name: name || key, total: 0, hits: 0, crits: 0, overkill: 0, max: 0, records: [] }; a.total += r.amount; a.hits++; if (r.crit) a.crits++; a.overkill += r.overkill || 0; a.max = Math.max(a.max, r.amount); a.records.push(r); }
    const rows = Object.values(by).map(a => ({ ...a, dps: +(a.total / dur).toFixed(1), sources: this.sources(a.records, mode) })).sort((x, y) => y.total - x.total); const top = rows[0]?.total || 1; for (const r of rows) r.pct = +(100 * r.total / top).toFixed(1); rows.duration = dur; rows.grand = rows.reduce((s, r) => s + r.total, 0); return rows;
  }
  /** Level 2: group an actor's records by source (via). */
  sources(records, mode = 'damage') { const by = {}; for (const r of records) { const key = mode === 'taken' ? (r.sourceName || r.source) + '·' + r.via : r.via; const s = by[key] ||= { via: r.via, name: mode === 'taken' ? `${r.sourceName || r.source}: ${r.viaName}` : r.viaName || r.via, dtype: r.dtype, total: 0, hits: 0, crits: 0, overkill: 0, max: 0, min: Infinity, hitsList: [] }; s.total += r.amount; s.hits++; if (r.crit) s.crits++; s.overkill += r.overkill || 0; s.max = Math.max(s.max, r.amount); s.min = Math.min(s.min, r.amount); s.hitsList.push(r); } const rows = Object.values(by).sort((a, b) => b.total - a.total); const top = rows[0]?.total || 1; for (const s of rows) { s.pct = +(100 * s.total / top).toFixed(1); s.avg = +(s.total / s.hits).toFixed(1); s.critPct = +(100 * s.crits / s.hits).toFixed(0); if (s.min === Infinity) s.min = 0; } return rows; }
  /** Level 3: the hits of one source (already in hitsList); this adds a compact description per hit. */
  describeHit(r) { const bits = [`${r.amount}`]; if (r.crit) bits.push('crit'); if (r.overkill) bits.push(`${r.overkill} overkill`); if (r.dtype && r.dtype !== 'physical') bits.push(r.dtype); if (r.tags?.length) bits.push(...r.tags); if (r.absorbed) bits.push(`${r.absorbed} absorbed`); return `${r.viaName || r.via} → ${r.targetName || r.target}: ${bits.join(', ')}`; }
  summary(scope = 'current') { const recs = this.records(scope); const dmg = recs.filter(r => r.kind === 'damage'); return { hits: dmg.length, damage: dmg.reduce((s, r) => s + r.amount, 0), healing: recs.filter(r => r.kind === 'heal').reduce((s, r) => s + r.amount, 0), crits: dmg.filter(r => r.crit).length, overkill: dmg.reduce((s, r) => s + (r.overkill || 0), 0), kills: recs.filter(r => r.killingBlow).length, fights: scope === 'all' ? this.fights.length : 1 }; }
  toJSON() { return { fights: this.fights.map(f => ({ ...f, records: f.records.slice(-2000) })), itemStats: this.itemStats }; }
  static fromJSON(j, opts) { const m = new Meter(opts); m.fights = j?.fights || []; m.itemStats = j?.itemStats || {}; return m; }
}
/** Make a small random fight for demos/tests. */
export function simulateFight(rng = Math.random, { heroes = ['Brannoc', 'Wren', 'Edric', 'Mirelle'], rounds = 8, foes = 3 } = {}) {
  const m = new Meter(); m.startFight('demo'); const via = [['attack', 'Longsword', 'physical', 'w_sword'], ['skill:cleave', 'Cleave', 'physical', null], ['skill:fireball', 'Fireball', 'fire', null], ['dot:burn', 'Burn', 'fire', null], ['proc:crit_bleed', 'Crit Bleed', 'bleed', null], ['skill:aimed_shot', 'Aimed Shot', 'physical', 'w_bow'], ['legendary:echo_cast', 'Echo Cast', 'arcane', null]];
  let t = 0; const foeHp = Array.from({ length: foes }, () => 40 + rng() * 40);
  for (let r = 1; r <= rounds; r++) for (const h of heroes) { t += 0.7; const v = via[Math.floor(rng() * via.length)]; const tgt = Math.floor(rng() * foes); const crit = rng() < 0.2; const amount = Math.round((6 + rng() * 18) * (crit ? 1.6 : 1)); const before = foeHp[tgt]; foeHp[tgt] = Math.max(0, before - amount); m.record({ t, source: h.toLowerCase(), sourceName: h, target: 'foe_' + tgt, targetName: 'Goblin ' + (tgt + 1), kind: 'damage', amount: Math.min(amount, Math.max(1, before)), overkill: Math.max(0, amount - before), crit, dtype: v[2], via: v[0], viaName: v[1], itemId: v[3], killingBlow: before > 0 && foeHp[tgt] === 0, tags: rng() < 0.1 ? ['blocked'] : [] }); if (foeHp[tgt] === 0) foeHp[tgt] = 30 + rng() * 30; if (h === 'Mirelle' && rng() < 0.5) { t += 0.3; m.record({ t, source: 'mirelle', sourceName: 'Mirelle', target: heroes[Math.floor(rng() * heroes.length)].toLowerCase(), targetName: 'ally', kind: 'heal', amount: Math.round(10 + rng() * 20), via: 'skill:heal', viaName: 'Heal', dtype: 'holy' }); } t += 0.4; m.record({ t, source: 'foe_' + tgt, sourceName: 'Goblin ' + (tgt + 1), target: h.toLowerCase(), targetName: h, kind: 'damage', amount: Math.round(3 + rng() * 9), via: 'attack', viaName: 'Claws', dtype: 'physical', tags: rng() < 0.15 ? ['blocked'] : [] }); }
  m.endFight(); return m;
}
