// Drill-down meter panel: bars per actor → sources → hits. Framework-free; call render(meter, container, state).
import { Meter } from './meter.js';
export function renderMeter(meter, root, state = {}) {
  state.mode ||= 'damage'; state.scope ||= 'current'; const el = (t, a = {}, ...k) => { const e = document.createElement(t); for (const [key, v] of Object.entries(a)) { if (key === 'class') e.className = v; else if (key === 'text') e.textContent = v; else if (key === 'html') e.innerHTML = v; else if (key.startsWith('on')) e.addEventListener(key.slice(2), v); else e.setAttribute(key, v); } for (const c of k) if (c != null) e.append(c); return e; };
  const rows = meter.report(state.mode, state.scope); const head = el('div', { class: 'meter-head' }, ...['damage', 'heal', 'taken'].map(m => el('button', { class: 'small' + (state.mode === m ? ' on' : ''), text: { damage: 'Damage done', heal: 'Healing', taken: 'Damage taken' }[m], onclick: () => { state.mode = m; state.actor = null; state.source = null; renderMeter(meter, root, state); } })), el('span', { class: 'spacer' }), el('select', { class: 'small', onchange: e => { state.scope = e.target.value; state.actor = null; state.source = null; renderMeter(meter, root, state); } }, el('option', { value: 'current', text: 'this fight' }), el('option', { value: 'all', text: `all fights (${meter.fights.length})` }), ...meter.fights.map(f => el('option', { value: f.id, text: f.label }))), el('span', { class: 'tiny', text: ` ${Math.round(rows.duration)}s · total ${rows.grand}` }));
  head.querySelector('select').value = state.scope; const list = el('div', { class: 'meter-list' }); const fmt = n => n.toLocaleString();
  if (!state.actor) { for (const r of rows) list.append(el('div', { class: 'meter-row', onclick: () => { state.actor = r.id; renderMeter(meter, root, state); } }, el('div', { class: 'meter-bar', style: `width:${r.pct}%` }), el('span', { class: 'meter-name', text: r.name }), el('span', { class: 'meter-val', text: `${fmt(r.total)} (${r.dps}/s) · ${r.hits} hits${r.crits ? ` · ${r.crits} crit` : ''}${r.overkill ? ` · ${r.overkill} overkill` : ''}` }))); if (!rows.length) list.append(el('p', { class: 'tiny', text: 'No records yet.' })); }
  else if (!state.source) { const a = rows.find(r => r.id === state.actor); list.append(el('div', { class: 'meter-crumb', onclick: () => { state.actor = null; renderMeter(meter, root, state); } }, el('b', { text: '‹ ' + (a?.name || state.actor) }), el('span', { class: 'tiny', text: ' · by source (click a bar for every hit)' }))); for (const s of a?.sources || []) list.append(el('div', { class: 'meter-row', onclick: () => { state.source = s.via + '|' + s.name; renderMeter(meter, root, state); } }, el('div', { class: 'meter-bar ' + (s.dtype || ''), style: `width:${s.pct}%` }), el('span', { class: 'meter-name', text: s.name }), el('span', { class: 'meter-val', text: `${fmt(s.total)} · ${s.hits} hits · avg ${s.avg} · max ${s.max} · ${s.critPct}% crit · ${s.dtype}` }))); }
  else { const a = rows.find(r => r.id === state.actor); const s = a?.sources.find(x => x.via + '|' + x.name === state.source); list.append(el('div', { class: 'meter-crumb', onclick: () => { state.source = null; renderMeter(meter, root, state); } }, el('b', { text: `‹ ${a?.name} · ${s?.name}` }), el('span', { class: 'tiny', text: ' · every hit' }))); const tbl = el('table', { class: 'meter-hits' }, el('thead', {}, el('tr', {}, ...['t', 'target', 'amount', 'crit', 'overkill', 'type', 'notes'].map(h => el('th', { text: h }))))); const tb = el('tbody'); for (const h of s?.hitsList || []) tb.append(el('tr', { class: h.crit ? 'crit' : '' }, el('td', { text: (+h.t).toFixed(1) }), el('td', { text: h.targetName || h.target }), el('td', { text: h.amount }), el('td', { text: h.crit ? '★' : '' }), el('td', { text: h.overkill || '' }), el('td', { text: h.dtype }), el('td', { text: [...(h.tags || []), h.killingBlow ? 'killing blow' : '', h.absorbed ? h.absorbed + ' absorbed' : ''].filter(Boolean).join(', ') }))); tbl.append(tb); list.append(tbl); }
  root.replaceChildren(head, list); return state;
}
export const METER_CSS = `.meter-head{display:flex;gap:6px;align-items:center;margin-bottom:6px;flex-wrap:wrap}.meter-head .spacer{flex:1}.meter-head button.on{background:#e08a2a;color:#1a1408;border-color:#e08a2a}.meter-row{position:relative;height:22px;margin:3px 0;background:#23202a;border-radius:4px;overflow:hidden;cursor:pointer;font-size:12px;line-height:22px}.meter-row:hover{outline:1px solid #e08a2a}.meter-bar{position:absolute;inset:0 auto 0 0;background:#3a6a9a;opacity:.85}.meter-bar.fire{background:#b04a2a}.meter-bar.arcane{background:#7a4ab0}.meter-bar.holy{background:#b0a04a}.meter-bar.bleed,.meter-bar.poison{background:#5a8a3a}.meter-bar.shadow,.meter-bar.void{background:#4a2a6a}.meter-name{position:relative;padding-left:6px;font-weight:600}.meter-val{position:absolute;right:6px;top:0;color:#eee}.meter-crumb{cursor:pointer;margin:4px 0 6px}.meter-hits{width:100%;border-collapse:collapse;font-size:11px}.meter-hits th,.meter-hits td{padding:2px 4px;border-bottom:1px solid #333;text-align:left}.meter-hits tr.crit td{color:#ffd040}`;
