// Game state + world rules: party/companions/bench, gold/materials/fame, zone graph + node handling, dialog and random
// events (with skill checks, flags, rewards), towns (act-gated services), dungeons, quests, save/load. No DOM.
import { makeRng, hashStr } from './rng.js';
import { Loot } from './loot.js';
import { createHero, gainXp, catchUp, refresh, hireCost, makeEnemy, equip, unequip, derive } from './rules.js';
import { MemoryBank } from '../../../lingo/js/memory.js';
import { RelationGraph } from '../../../lingo/js/relations.js';
import { Meter } from '../../../meters/js/meter.js';
const SAVE_KEY = 'playground:emberveil:save:v1';
export const TOWNS = { 1: { name: 'Emberglen', services: ['merchant', 'tavern', 'cleric'] }, 2: { name: 'Ashfort', services: ['merchant', 'tavern', 'cleric', 'blacksmith', 'trainer'] }, 3: { name: 'Ironhold Bastion', services: ['merchant', 'tavern', 'cleric', 'blacksmith', 'trainer', 'enchanter'] }, 4: { name: 'Starfall Haven', services: ['merchant', 'tavern', 'cleric', 'blacksmith', 'trainer', 'enchanter', 'blackmarket'] }, 5: { name: 'The Last Bastion', services: ['merchant', 'tavern', 'cleric', 'blacksmith', 'trainer', 'enchanter', 'blackmarket'] }, 6: { name: 'Drakehold', services: ['merchant', 'tavern', 'cleric', 'blacksmith', 'trainer', 'enchanter', 'blackmarket'] } };
export const VEHICLES = { none: { name: 'On foot', legs: 3, rationEvery: 1, attack: 0, difficulty: 0, price: 0, desc: 'Three nodes a day. One ration a day.' }, mule: { name: 'Pack mule', legs: 3, rationEvery: 2, attack: 0, difficulty: 0, price: 60, desc: 'Carries the food: a ration lasts two days. Still three nodes a day.' }, wagon: { name: 'Wagon', legs: 4, rationEvery: 2, attack: -0.15, difficulty: 0, price: 180, desc: 'Four nodes a day, rations last two days, high sides deter night raiders (−15%).' }, ox_cart: { name: 'Ox cart', legs: 2, rationEvery: 3, attack: -0.3, difficulty: -1, price: 120, desc: 'Slow (two nodes a day) but a ration lasts three days and oxen scare off small raiders (−30%, weaker attacks).' }, war_wagon: { name: 'War wagon', legs: 3, rationEvery: 2, attack: -0.45, difficulty: -1, price: 420, desc: 'Armoured. Night attacks are rare (−45%) and weaker; the party starts night fights behind a barrier.' }, coach: { name: 'Fast coach', legs: 5, rationEvery: 1, attack: 0.2, difficulty: 1, price: 350, desc: 'Five nodes a day. Loud and rich-looking: night attacks are likelier (+20%) and larger.' }, dragon_sled: { name: 'Dragon sled', legs: 6, rationEvery: 2, attack: 0.4, difficulty: 2, price: 900, act: 6, desc: 'Six nodes a day, pulled by something that should not be tame. Everything hunts it (+40%, much larger attacks).' } };
export const SUPPLY_KINDS = { ration: { name: 'Ration', icon: '🍞', price: 4, desc: 'One day of food for the party.' }, bandages: { name: 'Bandages', icon: '🩹', price: 12, desc: 'Out of combat: heals one hero 30% of max HP.' }, torch: { name: 'Torches', icon: '🔥', price: 3, desc: 'A lit camp: night attack chance −10% for one rest.' }, tent: { name: 'Tent', icon: '⛺', price: 90, desc: 'Reusable. Rest recovers 15% HP.' } };
export const ACT_NAMES = { 0: 'Prologue · The Lonely Road', 1: 'Act I · The Goblin Frontier', 2: 'Act II · The Ashen Wastes', 3: 'Act III · The Hell Breach', 4: 'Act IV · The Cosmic Void', 5: 'Act V · The Primordial Abyss', 6: "Act VI · The Dragon's Reach" };
export const MAIN_QUESTS = [{ id: 'mq_act1', title: 'Blood at the Border', act: 1, boss: 'border_boss', text: 'Goblin warbands raid the border with unnatural discipline. Find who commands them.' }, { id: 'mq_act2', title: 'Embers Over Cinderhold', act: 2, boss: 'plateau_boss', text: 'Follow the corruption into the Ashen Wastes and find Silas\'s missing daughter.' }, { id: 'mq_act3', title: 'The Veil Breach', act: 3, boss: 'breach_boss', text: 'Cross the breach into a Hell already fracturing. Confront Silas at Dreadhearth.' }, { id: 'mq_act4', title: 'Shards of the Architect', act: 4, boss: 'core_boss', text: 'Kaela Thorne needs three void shards to track the cult through the rift.' }, { id: 'mq_act5', title: 'The Architect', act: 5, boss: 'rift_boss', text: 'The hooded scholar was the Architect all along. Reach the place where reality was made.' }, { id: 'mq_act6', title: 'The Dragon King', act: 6, boss: 'dragonking_boss', text: 'Bahamorth\'s heart beats beneath three scales of dragon-steel.' }];

export class Game {
  constructor(data) { this.d = data; this.loot = new Loot(data.items); this.zones = Object.fromEntries(Object.values(data.zones).flat().filter(z => z?.id).map(z => [z.id, z])); this.zoneOrder = Object.values(data.zones).flat().filter(z => z?.id).map(z => z.id); this.reset(); }
  reset() { this.party = []; this.companions = []; this.bench = []; this.inventory = []; this.materials = { iron_scrap: 0, magic_essence: 0, rare_dust: 0, legend_core: 0 }; this.gold = 150; this.fame = 0; this.act = 0; this.zoneId = 'prologue'; this.nodeId = 'start'; this.unlockedZones = ['prologue']; this.visited = { prologue: ['start'] }; this.cleared = []; this.usedNodes = []; this.flags = {}; this.seenEvents = []; this.completedBosses = []; this.completedDungeons = []; this.quests = { active: [], done: [] }; this.kills = 0; this.rareFound = 0; this.ngPlus = 0; this.seed = Math.floor(Math.random() * 1e9); this.rng = makeRng(this.seed); this.log = []; this.day = 1;
    this.nemeses = []; this.namedSlain = []; this.namedSeen = []; this.supplies = { ration: 6, bandages: 1, torch: 2, tent: 0 }; this.vehicle = 'none'; this.legsUsed = 0; this.exhaustion = 0; this.fedToday = true; this.lootLog = []; this.banks = {}; this.relations = new RelationGraph(this.d.relations || { dimensions: {}, opinionWeights: {}, tags: [], events: {}, memoryEvents: {} }); this.meter = new Meter({ maxFights: 60 }); this.hour = 8; this.restLog = []; }
  // ---------- memory & feelings
  get now() { return (this.day - 1) * 24 + this.hour; }
  bank(id, traits = []) { if (!this.banks[id]) this.banks[id] = new MemoryBank({ ownerId: id, traits, eventTypes: this.d.events?.types || {}, lexicon: this.d.lexicon || null }); return this.banks[id]; }
  traitsOf(id) { return [...this.party, ...this.bench, ...this.companions].find(h => h.id === id)?.speech?.traits || []; }
  partyIds({ companions = true } = {}) { return [...this.party.map(h => h.id), ...(companions ? this.companions.map(c => c.id) : [])]; }
  /** Every participant remembers; feelings between them move (relations.json memoryEvents). */
  remember(event) { event.time = event.time ?? this.now; for (const id of event.participants || []) this.bank(id, this.traitsOf(id)).remember(event, this.now); try { this.relations.applyMemoryEvent(event, { traitsOf: id => this.traitsOf(id), now: this.now }); } catch {} this.log.push({ at: this.now, type: event.type, details: event.details }); return event; }
  // ---------- days, travel legs, supplies, vehicles
  vehicleDef() { return VEHICLES[this.vehicle] || VEHICLES.none; }
  legsPerDay() { return this.vehicleDef().legs; }
  legsLeft() { return Math.max(0, this.legsPerDay() - this.legsUsed); }
  canMove() { return this.legsLeft() > 0; }
  /** Spend a travel leg (called on every node move). Returns false if the party must rest first. */
  spendLeg() { if (!this.canMove()) return false; this.legsUsed++; this.hour = Math.min(22, 8 + Math.round(14 * this.legsUsed / this.legsPerDay())); return true; }
  /** Night attack odds for the current zone before resting: base by act, vehicle and torches. */
  nightAttack() { const act = this.zone()?.act || 0; const base = 0.15 + act * 0.06; const v = this.vehicleDef(); const torch = this.supplies.torch > 0 ? -0.1 : 0; const town = this.node()?.type === 'town'; const chance = town ? 0 : Math.max(0, Math.min(0.95, base + v.attack + torch)); return { chance, difficulty: v.difficulty, base, vehicle: v.attack, torch, town }; }
  /** Rest for the night: eat (or suffer), tick memories/relations, maybe get attacked. Does NOT heal by itself. Returns what happened. */
  rest({ eatExtra = false, useTorch = true } = {}) {
    const v = this.vehicleDef(); const out = { ate: false, extra: false, exhaustion: 0, healed: 0, day: this.day + 1, torchUsed: false };
    const needsFood = (this.day % v.rationEvery) === 0 || v.rationEvery === 1; if (needsFood) { if (this.supplies.ration > 0) { this.supplies.ration--; out.ate = true; this.fedToday = true; } else { this.fedToday = false; } } else { out.ate = true; this.fedToday = true; }
    if (this.fedToday) this.exhaustion = Math.max(0, this.exhaustion - 1); else this.exhaustion = Math.min(5, this.exhaustion + 1); out.exhaustion = this.exhaustion;
    if (eatExtra && this.supplies.ration > 0) { this.supplies.ration--; out.extra = true; for (const h of this.party) if (h.alive) { const heal = Math.round(h.maxHp * 0.3); h.hp = Math.min(h.maxHp, h.hp + heal); out.healed += heal; } }
    if (this.supplies.tent > 0) for (const h of this.party) if (h.alive) h.hp = Math.min(h.maxHp, h.hp + Math.round(h.maxHp * 0.15));
    if (useTorch && this.supplies.torch > 0 && this.node()?.type !== 'town') { this.supplies.torch--; out.torchUsed = true; }
    for (const h of [...this.party, ...this.companions]) { if (!h.alive) { h.alive = true; h.hp = Math.max(1, h.hp); } h.mp = h.maxMp; h.statuses = []; const d = h.derived; if (d?.hpRegen) h.hp = Math.min(h.maxHp, h.hp + d.hpRegen * 8); }
    this.remember({ type: 'meal', participants: this.partyIds(), bindings: { food: { id: out.ate ? 'trail_ration' : 'hardtack' }, place: { id: this.zoneId } }, details: { quality: out.extra ? 'good' : out.ate ? 'cold' : 'terrible' } });
    this.day++; this.hour = 8; this.legsUsed = 0; this.restLog.push({ day: this.day, zone: this.zoneId, ...out }); return out;
  }
  /** Exhaustion penalty: −10% hit/dodge/damage per stack (applied in derive via game.exhaustionMult). */
  exhaustionMult() { return Math.max(0.5, 1 - 0.1 * this.exhaustion); }
  buySupply(kind, n = 1) { const def = SUPPLY_KINDS[kind]; if (!def) return false; const cost = def.price * n; if (this.gold < cost) return false; this.gold -= cost; this.supplies[kind] = (this.supplies[kind] || 0) + n; return true; }
  useBandage(hero) { if ((this.supplies.bandages || 0) <= 0) return false; this.supplies.bandages--; hero.hp = Math.min(hero.maxHp, hero.hp + Math.round(hero.maxHp * 0.3)); return true; }
  buyVehicle(id) { const v = VEHICLES[id]; if (!v || this.gold < v.price) return false; if (v.act && this.act < v.act) return false; this.gold -= v.price; this.vehicle = id; return true; }
  /** Log loot so conversations can talk about it (found when, equipped or not, better/worse than what it replaced). */
  logLoot(item, { holder = null, equipped = false, replaced = null, delta = 0 } = {}) { const e = this.lootLog.find(l => l.itemId === item.id); if (e) { Object.assign(e, { holder: holder || e.holder, equipped, replaced: replaced || e.replaced, delta: delta || e.delta }); return e; } const l = { itemId: item.id, item, holder, day: this.day, equipped, replaced, delta }; this.lootLog.push(l); if (this.lootLog.length > 80) this.lootLog.shift(); return l; }
  // ---------- party
  classDef(id) { return this.d.classes.classes.find(c => c.id === id); }
  build(classId) { const list = this.d.builds.presets || this.d.builds.builds || (Array.isArray(this.d.builds) ? this.d.builds : Object.values(this.d.builds).flat()); return list.find?.(b => b.class === classId) || null; }
  makeHero(classId, name, level = 1, blueprint = null) { const h = createHero({ name, classId, level, classDef: this.classDef(classId), build: this.build(classId), blueprint, loot: this.loot, skills: this.d.skills.skills }); if (blueprint) { h.avatar = blueprint.avatar; h.voice = blueprint.voice; h.speech = blueprint.speech; h.short = blueprint.short || name.split(' ')[0]; h.pronouns = blueprint.pronouns; } h.short = h.short || name.split(' ')[0]; return h; }
  addHero(h) { if (this.party.length < 4) this.party.push(h); else this.bench.push(h); return h; }
  addCompanion(c) { if (this.companions.length < 4) { this.companions.push(c); c.speech = c.speech || { traits: ['loyal'] }; this.remember({ type: 'join', participants: [...this.party.map(h => h.id), c.id], bindings: { newcomer: { id: c.id }, place: { id: this.zoneId } }, details: { impression: 'brought food, which helped' } }); return true; } return false; }
  makeCompanion(def, level = null) { const L = Math.max(1, Math.round(level || this.avgLevel())); const P = def.power || 1; const hp = Math.round(30 * P + 8 * P * L); const c = { id: 'c_' + def.id + '_' + Math.random().toString(36).slice(2, 6), name: def.name, templateId: def.id, className: def.className || 'Companion', isCompanion: true, isHero: false, level: L, attrs: { ...(def.attrs || { STR: 8, DEX: 8, INT: 4, CON: 8 }) }, equipment: {}, skills: [], talents: {}, passiveRanks: {}, alive: true, statuses: [], cooldowns: {}, power: P, description: def.description, maxHp: hp, hp: hp, maxMp: 10, mp: 10, dmg: [Math.max(1, Math.round(3 + P + P * L)), Math.max(2, Math.round(5 + 2 * P + 1.5 * P * L))] }; return c; }
  avgLevel() { return this.party.length ? this.party.reduce((s, h) => s + h.level, 0) / this.party.length : 1; }
  alive() { return this.party.filter(h => h.alive && h.hp > 0); }
  fighters() { return [...this.party, ...this.companions].filter(x => x.alive); }
  // ---------- map
  zone(id = this.zoneId) { return this.zones[id]; }
  node(id = this.nodeId, zoneId = this.zoneId) { return this.zone(zoneId)?.nodes.find(n => n.id === id); }
  nodeKey(n = this.node()) { return `${this.zoneId}:${n.id}`; }
  isVisited(nId) { return (this.visited[this.zoneId] || []).includes(nId); }
  isCleared(nId) { return this.cleared.includes(`${this.zoneId}:${nId}`); }
  isUsed(nId) { return this.usedNodes.includes(`${this.zoneId}:${nId}`); }
  /** Nodes the party may travel to: exits of the current node plus any visited node (fast travel). */
  reachable() { const cur = this.node(); const set = new Set([...(cur?.exits || []), ...(this.visited[this.zoneId] || [])]); set.delete(this.nodeId); return [...set]; }
  canTravel(nId) { return this.reachable().includes(nId); }
  travel(nId) { if (!this.canTravel(nId)) return null; if (!this.spendLeg()) return null; this.nodeId = nId; (this.visited[this.zoneId] ||= []).push(nId); this.visited[this.zoneId] = [...new Set(this.visited[this.zoneId])]; return this.node(); }
  nextZoneId(zoneId = this.zoneId) { return this.d.zoneTables.ZONE_UNLOCK_MAP[zoneId] || null; }
  unlockNextZone() { const nz = this.nextZoneId(); if (nz && !this.unlockedZones.includes(nz)) this.unlockedZones.push(nz); const bossAct = this.d.zoneTables.ACT_BOSS_ZONES[this.zoneId]; if (bossAct != null) { this.act = Math.max(this.act, bossAct); this.flags['act' + (bossAct - 1) + '_complete'] = true; } return nz; }
  startNodeId(zoneId) { const z = this.zone(zoneId); if (!z) return 'start'; if (z.nodes.some(n => n.id === 'start')) return 'start'; const targets = new Set(z.nodes.flatMap(n => n.exits || [])); return (z.nodes.find(n => !targets.has(n.id)) || z.nodes[0]).id; }
  enterZone(zoneId) { if (!this.unlockedZones.includes(zoneId)) return false; this.zoneId = zoneId; this.nodeId = this.startNodeId(zoneId); (this.visited[zoneId] ||= []).push(this.nodeId); this.act = Math.max(this.act, this.zone(zoneId).act); this.remember({ type: 'travel', participants: this.partyIds(), bindings: { place: { id: zoneId } }, details: {} }); return true; }
  townFor(zoneId = this.zoneId) { const act = Math.max(1, this.zone(zoneId)?.act || 1); return { id: 'town_act' + act, act, ...TOWNS[Math.min(6, act)] }; }
  /** What happens at a node: returns { kind, ... } for the UI to run. Memory rules: cleared combat stays cleared; one-shot nodes stay used. */
  enter(n = this.node()) {
    const key = `${this.zoneId}:${n.id}`; const first = !this.isUsed(n.id);
    if (n.type === 'town') return { kind: 'town', town: this.townFor(), node: n };
    if (['combat', 'ambush', 'challenge', 'boss'].includes(n.type)) { if (this.isCleared(n.id)) return { kind: 'cleared', node: n }; let enc = this.encounter(n.encounter, n.type === 'boss');
      if (n.type === 'challenge' && enc) { const st = this.staticNamed()[0]; enc = this.namedEncounter({ staticDef: st || null, templateId: st ? null : enc.enemies[0]?.templateId, base: enc }) || enc; }
      else if (n.type !== 'boss' && enc) { const r = this.rng(); if (this.nemeses.length && r < 0.2) enc = this.nemesisEncounter() || enc; else if (r < 0.28) enc = this.namedEncounter({ base: enc }) || enc; }
      return { kind: 'combat', node: n, encounter: enc, boss: n.type === 'boss', named: enc?.named || null }; }
    if (n.type === 'dialog') { if (!first) return { kind: 'quiet', node: n, text: 'Nothing more happens here.' }; const ev = this.d.dialogs.DIALOG_EVENTS[n.dialogEventId] || this.randomEvent(); return ev ? { kind: 'event', node: n, event: ev } : { kind: 'quiet', node: n, text: n.name }; }
    if (n.type === 'shrine') { if (!first) return { kind: 'quiet', node: n, text: 'The shrine is silent now.' }; this.usedNodes.push(key); const t = n.shrineType || 'heal'; for (const h of [...this.party, ...this.companions]) { h.alive = true; h.hp = h.maxHp; if (t === 'fullrestore') h.mp = h.maxMp; } if (t === 'empower') this.flags.empowered = 1; return { kind: 'shrine', node: n, shrineType: t, text: t === 'heal' ? 'Cool water and old stone. Everyone is whole again.' : t === 'fullrestore' ? 'Body and mind restored.' : 'Strength hums in your limbs. Your next fight starts with a blessing.' }; }
    if (n.type === 'treasure') { if (!first) return { kind: 'quiet', node: n, text: 'The cache is empty.' }; this.usedNodes.push(key); const g = 60 + this.rng.int(0, 59); this.gold += g; const item = this.rng() < 0.5 ? this.loot.generate(this.rng.pick(['ring', 'necklace', 'light_chest', 'sword', 'wand']), 'magic', 'medium', { rng: this.rng }) : null; if (item) this.inventory.push(item); return { kind: 'treasure', node: n, gold: g, item }; }
    if (n.type === 'skillCheck') { if (!first) return { kind: 'quiet', node: n, text: 'Already dealt with.' }; return { kind: 'skillCheck', node: n, check: n.skillCheck }; }
    if (n.type === 'lore') { if (!first) return { kind: 'quiet', node: n, text: n.name }; this.usedNodes.push(key); return { kind: 'lore', node: n, text: this.loreText(n) }; }
    if (n.type === 'dungeon') { const dg = Object.values(this.d.dungeons.DUNGEONS).find(x => x.parentZone === this.zoneId); return dg ? { kind: 'dungeon', node: n, dungeon: dg, done: this.completedDungeons.includes(dg.id) } : { kind: 'quiet', node: n, text: n.name }; }
    return { kind: 'quiet', node: n, text: n.name };
  }
  loreText(n) { const z = this.zone(); const acts = { 0: 'The road is quiet in the way roads are quiet just before they are not.', 1: 'Rot-rings in the fields, all the same size. Iris Vael would call it a pattern. The farmers call it Tuesday.', 2: 'The Ashen Veil worked here. You can tell by what is missing.', 3: 'Something in Hell is afraid. That is new.', 4: 'The sky is simply gone. What is left keeps its own counsel.', 5: 'This is where reality was made. It was not made carefully.', 6: 'Dragon-steel, three scales thick. The heart beneath still beats.' }; return `${n.name}. ${acts[z.act] || ''}`; }
  /** Resolve a node skill check with the party's best attribute + d20. */
  resolveSkillCheck(n) { const c = n.skillCheck; const best = Math.max(...this.alive().map(h => derive(h, this.loot)[c.stat] ?? h.attrs[c.stat] ?? 8)); const roll = 1 + this.rng.int(0, 19); const ok = best + roll >= c.dc; this.usedNodes.push(`${this.zoneId}:${n.id}`); if (ok) { if (c.success?.gold) this.gold += c.success.gold; if (c.success?.item) { const it = this.loot.generate(c.success.item, 'magic', 'medium', { rng: this.rng }); if (it) this.inventory.push(it); } } else if (c.failure?.hpLoss) for (const h of this.alive()) h.hp = Math.max(1, h.hp - c.failure.hpLoss); return { ok, roll, best, dc: c.dc, text: ok ? c.success?.text : c.failure?.text }; }
  // ---------- encounters
  encounter(id, boss = false) { const enc = this.d.encounters.encounters[id]; if (!enc) return null; const foes = []; let i = 0; const heroes = Math.max(1, this.party.length); enc.enemies.forEach((g, gi) => { for (let k = 0; k < (g.count || 1); k++) { const tpl = this.d.enemies.entities[g.ref] || this.d.bosses.entities[g.ref]; if (!tpl) continue; const isBoss = boss && (gi === 0) && (!!this.d.bosses.entities[g.ref] || g.count === 1); const e = makeEnemy(tpl, { act: Math.max(1, this.act), heroes, ngPlus: this.ngPlus, boss: isBoss, overrides: g.overrides || {}, index: i++ }); e.group = gi; if (this.rng() < 0.05 && !isBoss) { e.champion = true; e.maxHp = Math.round(e.maxHp * 1.5); e.hp = e.maxHp; e.dmg = e.dmg.map(x => Math.round(x * 1.3)); e.name = 'Champion ' + e.name; } foes.push(e); } }); return { id, name: enc.name, enemies: foes }; }
  // ---------- named enemies (super-uniques, random names, nemeses)
  named() { return this.d.named || { static: [], modifiers: { tough: '+8 armor', fast: 'acts twice' }, titles: ['the Cruel', 'the Loud'], syllables: { human: ['Mor', 'Vel'] }, suffixes: { human: ['wick', 'gan'] } }; }
  raceOf(templateId) { if (/goblin|kobold/.test(templateId)) return 'goblin'; if (/demon|imp|fiend|hell|fel|archfiend/.test(templateId)) return 'demon'; if (/skeleton|ghoul|wraith|lich|undead|bone|shade|wight/.test(templateId)) return 'undead'; if (/wolf|bear|spider|hound|drake|dragon|wyrm|worm|horror|titan|elemental|golem/.test(templateId)) return 'beast'; if (/void|star|cosmic|reality|shard|prophet|null/.test(templateId)) return 'void'; return 'human'; }
  /** Random named enemy built on a template: name from syllables, a title, 1–2 modifiers, +50% hp/+25% dmg, better loot. */
  namedEnemy(templateId, { rng = this.rng, mods = null, name = null, title = null, staticId = null } = {}) {
    const tpl = this.d.enemies.entities[templateId] || this.d.bosses.entities[templateId]; if (!tpl) return null; const N = this.named(); const race = this.raceOf(templateId);
    const nm = name || (rng.pick(N.syllables[race] || N.syllables.human) + rng.pick(N.suffixes[race] || N.suffixes.human)); const tt = title ?? (rng() < 0.7 ? rng.pick(N.titles) : '');
    const e = makeEnemy(tpl, { act: Math.max(1, this.act), heroes: Math.max(1, this.party.length), ngPlus: this.ngPlus, overrides: {}, index: 90 + Math.floor(rng() * 9) }); const chosen = mods || rng.shuffle(Object.keys(N.modifiers)).slice(0, rng() < 0.5 ? 1 : 2);
    e.named = true; e.staticId = staticId; e.baseName = tpl.name; e.name = nm + (tt ? ' ' + tt : ''); e.short = nm; e.title = tt; e.mods = chosen; e.maxHp = Math.round(e.maxHp * 1.5); e.hp = e.maxHp; e.dmg = e.dmg.map(x => Math.round(x * 1.25)); e.xpValue = Math.round(e.xpValue * 2); e.gold = e.gold.map(x => x * 3);
    for (const m of chosen) { if (m === 'tough') e.armor += 8; if (m === 'fast') e.extraActionsEachRound = 1; if (m === 'regen') e.regenPct = 0.05; if (m === 'thorns') e.thorns = 0.2; if (m === 'fiery') e.statusOnHit = [...(e.statusOnHit || []), { type: 'burn', chance: 0.6, duration: 2, power: Math.max(4, Math.round(e.dmg[1] * 0.3)) }]; if (m === 'vampiric') e.lifeSteal = 0.3; if (m === 'cursed') e.statusOnHit = [...(e.statusOnHit || []), { type: 'curse', chance: 0.5, duration: 2, power: 20 }]; if (m === 'colossal') { e.maxHp = Math.round(e.maxHp * 1.5); e.hp = e.maxHp; e.dmg = e.dmg.map(x => Math.round(x * 1.2)); e.big = true; } }
    return e;
  }
  staticNamed(zoneId = this.zoneId) { return this.named().static.filter(n => n.zone === zoneId && !this.namedSlain.includes(n.id)); }
  /** Build a named-led encounter: the named enemy plus followers from the base encounter (or the zone pool). */
  namedEncounter({ staticDef = null, templateId = null, base = null, rng = this.rng } = {}) {
    const pool = this.d.zones.ZONE_ENCOUNTER_POOLS[this.zoneId] || []; const enc = base || this.encounter(rng.pick(pool)) || { id: 'named', name: 'named', enemies: [] }; const tid = staticDef?.base || templateId || enc.enemies[0]?.templateId; if (!tid) return null;
    const leader = staticDef ? this.namedEnemy(tid, { rng, mods: staticDef.mods, name: staticDef.name, title: staticDef.title, staticId: staticDef.id }) : this.namedEnemy(tid, { rng }); if (!leader) return null; leader.look = staticDef?.look || null; leader.lore = staticDef?.lore || null; leader.group = 0;
    const followers = enc.enemies.slice(0, leader.mods.includes('summoner') ? 4 : 2); enc.enemies = [leader, ...followers]; enc.name = `${leader.name}${followers.length ? ' and followers' : ''}`; enc.named = leader; if (!this.namedSeen.includes(leader.name)) this.namedSeen.push(leader.name); return enc;
  }
  /** A nemesis is a named enemy that beat the party. It escapes and comes back stronger in name (a new title), same power. */
  addNemesis(leader) { const ex = this.nemeses.find(n => n.name === leader.short || n.name === leader.name); const N = this.named(); if (ex) { ex.defeats++; ex.title = ex.defeats >= 3 ? 'the Unkillable' : ex.defeats === 2 ? 'the Twice-Victorious' : ex.title; return ex; } const n = { name: leader.short || leader.name, title: leader.title || '', templateId: leader.templateId, mods: leader.mods || [], staticId: leader.staticId || null, look: leader.look || null, defeats: 1, zone: this.zoneId, sinceDay: this.day }; n.title = n.title || N.titles[Math.floor(this.rng() * N.titles.length)]; this.nemeses.push(n); this.remember({ type: 'nemesis', participants: this.partyIds(), bindings: { foe: { id: leader.templateId }, place: { id: this.zoneId } }, details: { name: n.name + ' ' + n.title, outcome: 'beat_us' } }); return n; }
  nemesisEncounter(rng = this.rng) { const cand = this.nemeses.filter(n => this.zone(n.zone)?.act <= (this.zone().act || 0) + 1); if (!cand.length) return null; const n = rng.pick(cand); const enc = this.namedEncounter({ templateId: n.templateId, rng }); if (!enc) return null; const L = enc.named; L.short = n.name; L.title = n.title; L.name = `${n.name} ${n.title}`.trim(); L.mods = n.mods; L.nemesis = n; L.look = n.look; enc.name = `${L.name} returns`; enc.nemesis = n; return enc; }
  /** After a combat with a named leader: slain → memory + bounty progress; escaped (party lost) → nemesis. */
  resolveNamed(enc, won) { const L = enc.named; if (!L) return null; if (won) { this.namedSlain.push(L.staticId || L.name); this.nemeses = this.nemeses.filter(n => n.name !== L.short && n.name !== L.name); this.remember({ type: 'nemesis', participants: this.partyIds(), bindings: { foe: { id: L.templateId }, place: { id: this.zoneId } }, details: { name: L.name, outcome: 'slain' } }); this.checkSideQuests(); return { slain: L }; } return { nemesis: this.addNemesis(L) }; }
  // ---------- side quests (bounty board)
  sideQuests() { return (this.d.sideQuests?.quests || []).filter(q => q.act <= Math.max(1, this.act)); }
  acceptSideQuest(id) { if (!this.quests.active.includes(id) && !this.quests.done.includes(id)) this.quests.active.push(id); }
  checkSideQuests() { const done = []; for (const id of [...this.quests.active]) { const q = (this.d.sideQuests?.quests || []).find(x => x.id === id); if (!q) continue; let ok = false; if (q.targetNode) ok = this.cleared.includes(`${q.zone}:${q.targetNode}`); if (q.targetEncounter) ok = (this.flags['enc_' + q.targetEncounter] || 0) > 0; if (q.targetNamed) ok = this.namedSlain.length >= q.targetNamed; if (ok) { this.quests.active = this.quests.active.filter(x => x !== id); this.quests.done.push(id); this.gold += q.gold; this.fame += Math.round(q.gold / 20); done.push(q); } } return done; }
  /** Journal: each hero's strongest memories as prose lines (needs a lingo instance), plus the day log. */
  journal(lingo, talk) { const out = []; for (const h of this.party) { const bank = this.banks[h.id]; if (!bank) continue; const sp = talk.speaker(h); const lines = bank.list(this.now).slice(0, 6).map(({ memory }) => { try { return lingo.speakAbout(memory, bank, this.now, { speaker: sp, scene: talk.scene(this.zoneId) }).text; } catch { return null; } }).filter(Boolean); out.push({ hero: h, lines }); } return out; }
  /** A night raid from the zone's pool, sized by vehicle difficulty. */
  nightEncounter() { const pool = this.d.zones.ZONE_ENCOUNTER_POOLS[this.zoneId] || []; if (!pool.length) return null; const enc = this.encounter(this.rng.pick(pool)); if (!enc) return null; const diff = this.vehicleDef().difficulty; if (diff < 0 && enc.enemies.length > 1) enc.enemies = enc.enemies.slice(0, Math.max(1, enc.enemies.length - 1)); if (diff > 0) { const extra = enc.enemies.slice(0, diff).map((e, i) => ({ ...JSON.parse(JSON.stringify(e)), id: e.id + '_n' + i, statuses: [], cooldowns: {} })); enc.enemies.push(...extra); } if (this.rng() < 0.25) { const led = this.nemeses.length && this.rng() < 0.5 ? this.nemesisEncounter() : this.namedEncounter({ base: enc }); if (led) { led.night = true; led.name = 'Night raid: ' + led.name; return led; } } enc.name = 'Night raid: ' + enc.name; enc.night = true; return enc; }
  /** After a victory: xp, gold, fame, drops; marks node cleared; boss → unlock next zone + quests. Returns a summary. */
  victory(node, enc, { revisit = false } = {}) {
    const alive = this.alive(); const avg = this.avgLevel(); const xpFind = alive.reduce((s, h) => s + (h.derived?.xpFind || 0), 0), goldFind = alive.reduce((s, h) => s + (h.derived?.goldFind || 0), 0), magicFind = alive.reduce((s, h) => s + (h.derived?.magicFind || 0), 0);
    let xp = 0, gold = 0; const drops = []; for (const e of enc.enemies) { xp += Math.round(e.xpValue * (1 + xpFind) * 3); gold += Math.round(this.rng.int(e.gold[0], e.gold[1]) * (1 + goldFind) * 1.2); this.kills++; const it = this.loot.zoneDrop(this.zoneId, this.rng, { revisit, magicFind, act: Math.max(1, this.act) }); if (it) drops.push(it); }
    const levelUps = []; for (const h of this.party) { if (!h.alive) continue; const got = Math.round(xp * catchUp(h.level, avg)); const ups = gainXp(h, got); if (ups) { refresh(h, this.loot); h.hp = h.maxHp; h.mp = h.maxMp; levelUps.push({ hero: h, ups }); this.remember({ type: 'levelup', participants: [h.id], bindings: {}, details: { level: h.level } }); } }
    const isBoss = node?.type === 'boss'; const fameMult = this.d.zoneTables.ZONE_FAME_MULT[this.zoneId] || 1; const fame = Math.round(enc.enemies.length * fameMult) + (isBoss ? Math.round(15 * fameMult) : 0); this.fame += fame; this.gold += gold;
    for (const it of drops) { this.inventory.push(it); if (['rare', 'legendary'].includes(it.rarity)) this.rareFound++; }
    if (node) this.cleared.push(`${this.zoneId}:${node.id}`); if (enc.id) this.flags['enc_' + enc.id] = (this.flags['enc_' + enc.id] || 0) + 1;
    const ids = this.partyIds(); const foe = enc.enemies[0]?.templateId; const wounded = this.party.some(h => h.hp <= h.maxHp / 2);
    this.remember({ type: 'combat', participants: ids, bindings: { foe: { id: foe, count: enc.enemies.length }, place: { id: this.zoneId }, ally: { id: ids[1] || ids[0] } }, details: { outcome: 'won', wounded, night: !!enc.night, boss: !!node && node.type === 'boss' } });
    for (const h of this.party) { if (!h.alive) this.remember({ type: 'wounded', participants: [h.id], bindings: { foe: { id: foe, count: 1 }, place: { id: this.zoneId } }, details: { down: true } }); else if (h.hp <= h.maxHp / 2) this.remember({ type: 'wounded', participants: [h.id], bindings: { foe: { id: foe, count: 1 }, place: { id: this.zoneId } }, details: { down: false } }); }
    for (const h of [...this.party, ...this.companions]) { const k = enc.killsBy?.[h.id] || 0; if (k > 0) this.remember({ type: 'kill', participants: [h.id], bindings: { foe: { id: foe, count: k }, place: { id: this.zoneId } }, details: { how: k >= 3 ? 'a long ugly struggle' : 'a clean stroke' } }); }
    for (const it of drops) { const finder = this.alive()[Math.floor(this.rng() * Math.max(1, this.alive().length))]; this.logLoot(it, { holder: finder?.id || null }); this.remember({ type: 'loot', participants: ids, bindings: { item: { id: it.baseKey }, place: { id: this.zoneId } }, details: { worth: it.rarity === 'legendary' ? 'a fortune' : it.rarity === 'rare' ? 'more than it looked' : 'a few coins', itemName: it.name } }); }
    let bossDrops = [], unlockedZone = null, questDone = null; const namedResult = this.resolveNamed(enc, true); if (namedResult?.slain) { const extra = this.loot.generate(this.rng.pick(['sword', 'heavy_chest', 'ring', 'necklace', 'staff', 'bow']), this.rng() < 0.3 ? 'legendary' : 'rare', 'high', { rng: this.rng }); if (extra) { extra.name = `${namedResult.slain.short}'s ${extra.baseName}`; drops.push(extra); this.inventory.push(extra); this.logLoot(extra); } } const sideDone = this.checkSideQuests();
    if (isBoss) { const bossId = enc.enemies.find(e => e.boss)?.templateId; if (bossId && !this.completedBosses.includes(node.id)) { this.completedBosses.push(node.id); this.completedBosses.push(bossId); bossDrops = this.loot.bossLoot(bossId, this.rng); this.inventory.push(...bossDrops); } unlockedZone = this.unlockNextZone(); const q = MAIN_QUESTS.find(q => q.boss === node.id); if (q && !this.quests.done.includes(q.id)) { this.quests.done.push(q.id); this.quests.active = this.quests.active.filter(x => x !== q.id); questDone = q; const next = MAIN_QUESTS.find(x => x.act === q.act + 1); if (next) this.quests.active.push(next.id); } }
    // survivors with a revive skill bring the fallen back at half hp
    const canRevive = alive.some(h => (h.skills || []).some(id => this.d.skills.skills[id]?.type === 'revive')); if (canRevive) for (const h of this.party) if (!h.alive) { h.alive = true; h.hp = Math.max(1, Math.floor(h.maxHp * 0.5)); }
    for (const h of this.party) if (!h.alive) { h.alive = true; h.hp = Math.max(1, Math.floor(h.maxHp * 0.25)); } // this prototype: no permadeath, fallen wake at 25% after the fight
    for (const c of this.companions) if (!c.alive) { c.alive = true; c.hp = Math.max(1, Math.floor(c.maxHp * 0.5)); }
    return { xp, gold, fame, drops, bossDrops, levelUps, unlockedZone, questDone, namedSlain: namedResult?.slain || null, sideDone };
  }
  defeat(enc = null) { if (enc?.named) this.resolveNamed(enc, false); for (const h of this.party) { h.alive = true; h.hp = Math.max(1, Math.floor(h.maxHp * 0.5)); h.mp = Math.floor(h.maxMp * 0.5); } for (const c of this.companions) { c.alive = true; c.hp = Math.max(1, Math.floor(c.maxHp * 0.5)); } this.gold = Math.floor(this.gold * 0.85); const town = this.zone().nodes.find(n => n.type === 'town'); this.nodeId = town ? town.id : this.startNodeId(); return { text: 'You wake in town with lighter purses and heavier heads.', lost: '15% of your gold' }; }
  // ---------- events (dialog + random)
  randomEvent() { const lvl = Math.round(this.avgLevel()); const pool = this.d.randomEvents.RANDOM_EVENTS.filter(e => e.minLevel <= lvl && (e.zone === 'any' || (Array.isArray(e.zone) ? e.zone.includes(this.zoneId) : e.zone === this.zoneId)) && !this.seenEvents.includes(e.id)); if (!pool.length) return null; const ev = this.rng.pick(pool); this.seenEvents.push(ev.id); return ev; }
  choiceAllowed(c) { const r = c.requires; if (!r) return true; if (r.inventoryItem) return this.inventory.some(i => i.baseKey === r.inventoryItem || i.id === r.inventoryItem) || !!this.flags['item_' + r.inventoryItem]; if (r.flag) return !!this.flags[r.flag]; if (r.gold) return this.gold >= r.gold; if (r.minLevel) return this.avgLevel() >= r.minLevel; if (r.class) return this.party.some(h => h.class === r.class); return true; }
  /** Pick a choice; returns { text, reward?, startCombat?, check? }. */
  choose(ev, choice) {
    let outcomeId = choice.outcome; let check = null;
    if (choice.skillCheck) { const c = choice.skillCheck; const best = Math.max(...this.alive().map(h => derive(h, this.loot)[c.stat] ?? 8)); const roll = 1 + this.rng.int(0, 19); const ok = best + roll >= c.dc; check = { ok, roll, best, dc: c.dc, stat: c.stat }; outcomeId = ok ? choice.outcomes?.pass : choice.outcomes?.fail; }
    if (choice.effect?.gold) this.gold = Math.max(0, this.gold + choice.effect.gold);
    const out = (ev.outcomes && ev.outcomes[outcomeId]) || (typeof outcomeId === 'string' && !ev.outcomes?.[outcomeId] ? { text: outcomeId } : { text: '' }); const res = { text: out.text || '', check, startCombat: choice.effect?.startCombat || out.startCombat || null, rewards: [] };
    if (out.setFlag) this.flags[out.setFlag] = true; if (out.reward) res.rewards = this.applyReward(out.reward); if (choice.reward) res.rewards.push(...this.applyReward(choice.reward));
    this.usedNodes.push(`${this.zoneId}:${this.nodeId}`); return res;
  }
  applyReward(r) {
    const out = []; if (r.gold) { this.gold = Math.max(0, this.gold + r.gold); out.push(`${r.gold > 0 ? '+' : ''}${r.gold} gold`); } if (r.xp) { for (const h of this.party) if (h.alive) { const ups = gainXp(h, r.xp); if (ups) refresh(h, this.loot); } out.push(`+${r.xp} xp`); }
    if (r.heal) { for (const h of this.party) if (h.alive) h.hp = Math.min(h.maxHp, h.hp + r.heal); out.push(`healed ${r.heal}`); } if (r.damage) { for (const h of this.alive()) h.hp = Math.max(1, h.hp - r.damage); out.push(`took ${r.damage} damage`); }
    if (r.item) { const base = this.loot.base(r.item); const it = base ? this.loot.generate(r.item, r.itemRarity || 'magic', 'medium', { rng: this.rng }) : null; if (it) { if (r.itemName) it.name = r.itemName; it.desc = r.itemDesc; this.inventory.push(it); out.push(`found ${it.name}`); } else { this.flags['item_' + r.item] = true; out.push(`obtained ${r.itemName || r.item}`); } }
    if (r.buildLoot) { const keys = { jewelry: ['ring', 'necklace'], weapon: ['sword', 'dagger', 'wand', 'shortbow', 'staff'], armor: ['light_chest', 'medium_chest'] }[r.buildLoot] || ['ring']; const it = this.loot.generate(this.rng.pick(keys), 'magic', 'medium', { rng: this.rng }); if (it) { this.inventory.push(it); out.push(`found ${it.name}`); } }
    if (r.companion) { const def = { ...r.companion, power: r.companion.power || 2 }; if (this.addCompanion(this.makeCompanion(def))) out.push(`${def.name} joins you`); else out.push(`${def.name} would join, but your kennel is full`); }
    if (r.setFlag) this.flags[r.setFlag] = true; if (r.tapItem) out.push(`tap weapon (not in this prototype): ${r.tapItem}`); return out;
  }
  /** Record what was said at camp so later talks can call it back. */
  rememberConversation(speakerId, withId, topic, said) { this.remember({ type: 'conversation', participants: [speakerId, withId], bindings: { with: { id: withId }, place: { id: this.zoneId } }, details: { topic, said: String(said).slice(0, 90), by: speakerId } }); }
  // ---------- towns
  merchantStock(town) { const key = 'stock:' + town.id + ':' + this.day; if (!this.flags[key]) this.flags[key] = this.loot.merchantStock(town.id, town.act, { seed: this.seed + this.day, ngPlus: this.ngPlus, fame: this.fame, heroLvl: Math.round(this.avgLevel()) }); return this.flags[key]; }
  buy(item, price, from) { if (this.gold < price) return false; this.gold -= price; const i = from.indexOf(item); if (i >= 0) from.splice(i, 1); this.inventory.push(item); return true; }
  sell(item) { const p = this.loot.sellPrice(item); this.gold += p; this.inventory = this.inventory.filter(i => i !== item); return p; }
  salvage(item) { const y = this.loot.salvage(item, this.rng); for (const [m, n] of Object.entries(y)) this.materials[m] = (this.materials[m] || 0) + n; this.inventory = this.inventory.filter(i => i !== item); return y; }
  /** Town cleric: full heal + a new day (free; the cleric does the healing, not the bed). */
  clericRest(town) { for (const h of [...this.party, ...this.companions]) { h.alive = true; h.hp = h.maxHp; h.mp = h.maxMp; h.statuses = []; } this.day++; this.hour = 8; this.legsUsed = 0; this.fedToday = true; this.exhaustion = 0; return 0; }
  hires(town) { const key = 'hires:' + town.id; if (!this.flags[key]) { const named = (this.d.companions.hires || []).filter(h => (h.level || 1) <= Math.max(3, this.avgLevel() + 2)); const walkIns = []; const rng = makeRng(this.seed + town.act * 77 + this.day); for (let i = 0; i < 3; i++) { const c = rng.pick(this.d.classes.classes); const lvl = Math.max(1, Math.round(this.avgLevel()) + rng.int(-1, 0)); walkIns.push({ id: 'walkin_' + c.id + '_' + i, name: null, class: c.id, level: lvl, cost: hireCost(lvl) }); } this.flags[key] = [...named.map(h => ({ id: h.id, name: h.name, class: h.class, level: h.level || 1, cost: Math.max(100, (h.level || 1) * 100), attrs: h.attrs, description: h.description })), ...walkIns]; } return this.flags[key]; }
  kennel() { return (this.d.companions.companions || []).filter(c => !c.narrative || true).map(c => ({ ...c, price: (c.power || 1) * 100 })); }
  // ---------- quests
  startQuests() { if (!this.quests.active.length && !this.quests.done.length) this.quests.active.push('mq_act1'); }
  // ---------- save
  toJSON() { const { d, loot, zones, zoneOrder, rng, banks, relations, meter, ...rest } = this; return { ...rest, v: 2, banks: Object.fromEntries(Object.entries(banks).map(([k, b]) => [k, b.toJSON()])), relations: relations.toJSON(), meter: meter.toJSON() }; }
  save() { try { localStorage.setItem(SAVE_KEY, JSON.stringify(this)); return true; } catch { return false; } }
  static hasSave() { return !!localStorage.getItem(SAVE_KEY); }
  static clearSave() { localStorage.removeItem(SAVE_KEY); }
  static load(data) { const raw = localStorage.getItem(SAVE_KEY); if (!raw) return null; const j = JSON.parse(raw); const g = new Game(data); const { banks, relations, meter, ...rest } = j; Object.assign(g, rest); g.banks = Object.fromEntries(Object.entries(banks || {}).map(([k, b]) => [k, MemoryBank.fromJSON(b, { eventTypes: data.events?.types || {}, lexicon: data.lexicon || null })])); g.relations = RelationGraph.fromJSON(relations || {}, data.relations || g.relations.model); g.meter = Meter.fromJSON(meter || {}, { maxFights: 60 }); g.supplies ||= { ration: 6, bandages: 1, torch: 2, tent: 0 }; g.vehicle ||= 'none'; g.lootLog ||= []; g.rng = makeRng(g.seed + (g.day || 1) * 1000 + (g.kills || 0)); for (const h of g.party.concat(g.bench)) refresh(h, g.loot); return g; }
}
export { equip, unequip, refresh, derive, hireCost, VEHICLES as VEHICLE_DEFS };
