import { test } from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
import { Lingo, Speaker } from '../../lingo/js/lingo.js'; import { MemoryBank } from '../../lingo/js/memory.js'; import { Conversations, factsFrom } from '../js/conversations.js'; import { Meter } from '../../meters/js/meter.js';
const J = p => JSON.parse(fs.readFileSync(new URL(p, import.meta.url)));
const lingo = new Lingo({ lexicon: J('../../lingo/data/lexicon.json'), grammar: J('../../lingo/data/grammar.json'), traits: J('../../lingo/data/traits.json') }); for (const e of J('../../lingo/data/packs/emberveil.json').entries) lingo.lexicon.add(e); lingo.invalidatePronunciations();
const topics = J('../data/topics.json'); const events = J('../../lingo/data/events.json').types;
function party() { const mk = (id, name, traits) => new Speaker({ id, name, lexicon: lingo.lexicon, speech: { traits } }); return [mk('a', 'Brannoc', ['gruff', 'brave']), mk('b', 'Wren', ['shy', 'kind']), mk('c', 'Edric', ['scholar', 'pompous'])]; }
test('nothing eligible without facts except free topics; a combat memory unlocks the recap with the right cast and bindings', () => {
  const conv = new Conversations({ lingo, topics }); const sp = party(); const empty = factsFrom({ heroes: sp.map(s => ({ id: s.id, equipment: {} })) }); const free = conv.eligible(sp, empty); assert.ok(free.every(e => !e.topic.requires.length));
  const banks = { b: new MemoryBank({ ownerId: 'b', eventTypes: events, lexicon: lingo.lexicon }) }; banks.b.remember({ type: 'combat', time: 10, participants: ['b'], bindings: { foe: { id: 'goblin_scout', count: 3 }, place: { id: 'thornwood' } }, details: { outcome: 'won', wounded: false } });
  const facts = factsFrom({ now: 12, banks, heroes: sp.map(s => ({ id: s.id, equipment: {} })) }); const el = conv.eligible(sp, facts).find(e => e.topic.id === 'fight_recap'); assert.ok(el); assert.equal(el.answerer.id, 'b'); assert.equal(el.bindings.foe.count, 3);
  const lines = conv.perform(el, { rng: () => 0.1 }); assert.ok(lines.length >= 3); assert.equal(lines[0].role, 'asker'); assert.equal(lines[1].speaker.id, 'b'); assert.ok(lines.some(l => /goblin scouts|Thornwood/.test(l.text)), lines.map(l => l.text).join(' | '));
});
test('gear requirements: kill counts from the meter, better/worse than the replaced item, items left in the bag', () => {
  const conv = new Conversations({ lingo, topics }); const sp = party(); const meter = new Meter(); meter.startFight('x'); for (let i = 0; i < 4; i++) meter.record({ t: i, source: 'a', sourceName: 'Brannoc', target: 'g', targetName: 'Goblin', kind: 'damage', amount: 10, via: 'attack', viaName: 'Longsword', itemId: 'w1', killingBlow: true }); meter.record({ t: 5, source: 'b', sourceName: 'Wren', target: 'g', targetName: 'Goblin', kind: 'damage', amount: 4, via: 'attack', viaName: 'Rusty Bow', itemId: 'w2' }); meter.endFight();
  const heroes = [{ id: 'a', equipment: { weapon: { id: 'w1', name: 'Sharp Longsword', baseKey: 'longsword', rarity: 'magic' } } }, { id: 'b', equipment: { weapon: { id: 'w2', name: 'Rusty Bow', baseKey: 'shortbow' } } }, { id: 'c', equipment: {} }];
  const lootLog = [{ itemId: 'w1', item: heroes[0].equipment.weapon, holder: 'a', day: 3, delta: 12, replaced: 'Iron Sword', equipped: true }, { itemId: 'w2', item: heroes[1].equipment.weapon, holder: 'b', day: 2, delta: -6, replaced: 'Longbow', equipped: true }, { itemId: 'r1', item: { id: 'r1', name: 'Copper Ring', baseKey: 'ring' }, holder: 'c', day: 1, equipped: false }];
  const facts = factsFrom({ now: 100, day: 4, heroes, meter, lootLog, party: { rations: 1 } }); const ids = conv.eligible(sp, facts).map(e => e.topic.id);
  for (const want of ['kill_count_brag', 'new_gear_better', 'new_gear_worse', 'bag_dust', 'rations_low', 'top_damage_ribbing']) assert.ok(ids.includes(want), want + ' in ' + ids.join(','));
  const brag = conv.eligible(sp, facts).find(e => e.topic.id === 'kill_count_brag'); assert.equal(brag.answerer.id, 'a'); const lines = conv.perform(brag, { rng: () => 0 }); assert.ok(lines[0].text.includes('4'), lines[0].text);
  const worse = conv.eligible(sp, facts).find(e => e.topic.id === 'new_gear_worse'); assert.equal(worse.answerer.id, 'b'); assert.equal(worse.bindings.gear.deltaAbs, 6);
});
test('talk() rotates topics and returns spoken lines with speech for the voice', () => { const conv = new Conversations({ lingo, topics }); const sp = party(); const facts = factsFrom({ heroes: sp.map(s => ({ id: s.id, equipment: {} })), party: { act: 2, rations: 5 } }); const seen = new Set(); for (let i = 0; i < 6; i++) { const lines = conv.talk(sp, facts, { rng: Math.random, tags: ['camp'] }); assert.ok(lines.length >= 2); seen.add(lines[0].topic); assert.ok(typeof lines[0].speech === 'string'); } assert.ok(seen.size >= 3, [...seen].join(',')); });
test('threads advance over days and objectives; variant generator multiplies lines; rare topics carry rewards', async () => {
  const { Threads, expandVariants } = await import('../js/conversations.js'); const threadsData = J('../data/threads.json'); const conv = new Conversations({ lingo, topics }); const th = new Threads({ conv, threads: threadsData }); const sp = party();
  const heroes = [{ id: 'a', equipment: {} }, { id: 'b', equipment: { weapon: { id: 'w2', name: 'Rusty Bow', baseKey: 'shortbow' } } }, { id: 'c', equipment: {} }]; const lootLog = [{ itemId: 'w2', item: heroes[1].equipment.weapon, holder: 'b', day: 2, delta: -6, replaced: 'Longbow', equipped: true }];
  const facts = factsFrom({ now: 50, day: 3, heroes, lootLog, party: { day: 3, nodesTravelled: 2 } }); const state = {}; const first = th.play(sp, facts, state, { rng: () => 0 }); assert.ok(first); assert.ok(first.lines.length >= 2); const id = first.thread.id; assert.equal(state[id].stage, 0);
  assert.equal(th.due(sp, facts, state).find(d => d.thread.id === id), undefined, 'not due the same day');
  const later = factsFrom({ now: 100, day: 6, heroes, lootLog, party: { day: 6, nodesTravelled: 9 } }); const due = th.due(sp, later, state).find(d => d.thread.id === id); if (state[id].objective) { assert.equal(due, undefined); state[id].objectiveDone = true; } assert.ok(th.due(sp, later, state).find(d => d.thread.id === id) || th.due(sp, later, state).length >= 0);
  const before = topics.topics.reduce((n, t) => n + t.lines.reduce((m, l) => m + l.variants.length, 0), 0); const added = expandVariants(topics, { perLine: 2 }); const after = topics.topics.reduce((n, t) => n + t.lines.reduce((m, l) => m + l.variants.length, 0), 0); assert.ok(added > 100); assert.equal(after, before + added);
  const rare = topics.topics.filter(t => t.tags.includes('rare')); assert.ok(rare.length >= 10); assert.ok(rare.every(t => t.reward)); const lines = new Conversations({ lingo, topics }).talk(sp, facts, { tags: ['rare'], rng: () => 0.2 }); assert.ok(lines.length >= 2);
});
