// Language debug mode: turn spoken lines into clickable words. Click a word → a popover with the pronunciation the voice
// will use (respelling + phonemes from our formant engine), the Lingo lexicon entry if the word is one (forms, plural…),
// and boxes to type a replacement pronunciation or a replacement word. Overrides apply on the fly (Lingo pronunciation
// table + formant custom dictionary), persist in localStorage, export/import as JSON, and can be sent to the dev server
// (POST /api/inbox/lang-overrides) so Claude can fold them into the data.
//   import { LangDebug } from '../../shared/langdebug.js';
//   const dbg = new LangDebug({ lingo, base: '../../' }); dbg.decorate(paragraphEl);   // call for every spoken line
//   dbg.enabled = true; dbg.mountSettings(el)  // toggle + import/export/submit buttons
const KEY = 'playground:lang-overrides:v1';
export class LangDebug {
  constructor({ lingo = null, base = '../../', formant = null } = {}) { this.lingo = lingo; this.base = base; this.formant = formant; this.enabled = false; this.overrides = this.load(); this.applyAll(); }
  load() { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } }
  save() { try { localStorage.setItem(KEY, JSON.stringify(this.overrides)); } catch {} }
  async g2p() { if (!this.formant) { try { this.formant = await import(this.base + 'voice-lab/js/engines/formant/g2p.js'); } catch (e) { console.warn('formant g2p not available', e); this.formant = null; } } return this.formant; }
  /** Phonemes the voice would use for a word (after overrides). */
  async phonemesFor(word) { const g = await this.g2p(); if (!g) return null; const spoken = this.spokenForm(word); try { const r = g.textToPhonemes(spoken); return r.words.map(w => `${w.text}: ${w.phones.join(' ')} (${w.source})`).join(' · '); } catch (e) { return String(e.message); } }
  /** What the speech string will contain for this word (Lingo pron table → espeak block) */
  spokenForm(word) { if (!this.lingo) return word; const prons = this.lingo.lexicon.pronunciations(); const p = prons[word] || prons[word.toLowerCase()]; if (!p) return word; const { respellToEspeak } = this.lingo.constructor._helpers || {}; return p.espeak ? `[[${p.espeak}]]` : p.respell ? `${word} (respell ${p.respell})` : word; }
  entryFor(word) { if (!this.lingo) return null; const w = word.toLowerCase(); for (const e of this.lingo.lexicon.all()) for (const [k, f] of Object.entries(e.forms || {})) if (String(f).toLowerCase() === w || String(f).toLowerCase() === word) return { entry: e, form: k }; return null; }
  /** Apply one override: { respell?, replace? }. respell → Lingo pron (+ formant custom via espeak block); replace → word substitution in lines. */
  apply(word, ov) { const w = word.toLowerCase(); this.overrides[w] = { ...(this.overrides[w] || {}), ...ov }; this.save(); this.applyOne(w, this.overrides[w]); }
  applyOne(w, ov) { if (!this.lingo) return; if (ov.respell) { const hit = this.entryFor(w); if (hit) { hit.entry.pron = { ...(hit.entry.pron || {}), respell: ov.respell }; } else this.lingo.lexicon.add({ id: 'pron_' + w, type: 'concept', forms: { sg: w }, tags: ['override'], pron: { respell: ov.respell } }); this.lingo.invalidatePronunciations(); } }
  applyAll() { for (const [w, ov] of Object.entries(this.overrides)) this.applyOne(w, ov); }
  remove(word) { delete this.overrides[word.toLowerCase()]; this.save(); const e = this.lingo?.lexicon.get('pron_' + word.toLowerCase()); if (e) { this.lingo.lexicon.entries.delete(e.id); this.lingo.invalidatePronunciations(); } }
  /** Word replacements for display + speech (applied by the host before speaking). */
  rewrite(text) { let out = text; for (const [w, ov] of Object.entries(this.overrides)) if (ov.replace) out = out.replace(new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi'), ov.replace); return out; }
  exportJSON() { return JSON.stringify({ v: 1, overrides: this.overrides }, null, 2); }
  importJSON(json) { const j = typeof json === 'string' ? JSON.parse(json) : json; this.overrides = { ...this.overrides, ...(j.overrides || j) }; this.save(); this.applyAll(); }
  async submit(extra = {}) { const res = await fetch(this.base + 'api/inbox/lang-overrides', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ overrides: this.overrides, ...extra, at: new Date().toISOString() }) }); return res.ok; }
  /** Make the words of a spoken line clickable (only when enabled). */
  decorate(el) { if (!this.enabled || !el || el.dataset.langdbg) return; el.dataset.langdbg = '1'; const walk = node => { for (const c of [...node.childNodes]) { if (c.nodeType === 3) { const frag = document.createDocumentFragment(); for (const part of c.nodeValue.split(/(\b[A-Za-z][A-Za-z'’-]*\b)/)) { if (/^[A-Za-z]/.test(part)) { const s = document.createElement('span'); s.className = 'langdbg-word' + (this.overrides[part.toLowerCase()] ? ' has-override' : ''); s.textContent = part; s.onclick = ev => { ev.stopPropagation(); this.popover(part, s); }; frag.append(s); } else frag.append(document.createTextNode(part)); } c.replaceWith(frag); } else if (c.nodeType === 1 && !c.classList.contains('langdbg-word')) walk(c); } }; walk(el); }
  async popover(word, anchor) { document.querySelector('.langdbg-pop')?.remove(); const w = word.toLowerCase(); const ov = this.overrides[w] || {}; const hit = this.entryFor(word); const ph = await this.phonemesFor(word); const pop = document.createElement('div'); pop.className = 'langdbg-pop'; const r = anchor.getBoundingClientRect(); pop.style.left = Math.min(window.innerWidth - 340, r.left) + 'px'; pop.style.top = (r.bottom + 6 + window.scrollY) + 'px';
    pop.innerHTML = `<b>${word}</b> <span class="tiny">${hit ? `lexicon: <a href="${this.base}lingo/#entry=${hit.entry.id}" target="_blank">${hit.entry.id}</a> (${hit.entry.type}, form ${hit.form})` : 'not a lexicon word'}</span><div class="tiny">phonemes: ${ph || 'n/a'}</div>${hit ? `<div class="tiny">forms: ${Object.entries(hit.entry.forms).map(([k, v]) => `${k}=${v}`).join(', ')}${hit.entry.pron?.respell ? ` · respell ${hit.entry.pron.respell}` : ''}</div>` : ''}<label class="tiny">Respell (e.g. AL-drik, syllables with dashes, CAPS = stress)<input data-k="respell" value="${ov.respell || hit?.entry?.pron?.respell || ''}"></label><label class="tiny">Replace the word in lines with<input data-k="replace" value="${ov.replace || ''}"></label><div class="row"><button class="small" data-act="apply">Apply</button><button class="small" data-act="say">▶ Hear it</button><button class="small" data-act="clear">Clear</button><button class="small" data-act="close">Close</button></div>`;
    pop.querySelector('[data-act=apply]').onclick = () => { const respell = pop.querySelector('[data-k=respell]').value.trim(); const replace = pop.querySelector('[data-k=replace]').value.trim(); this.apply(word, { respell: respell || undefined, replace: replace || undefined }); anchor.classList.add('has-override'); pop.remove(); }; pop.querySelector('[data-act=clear]').onclick = () => { this.remove(word); anchor.classList.remove('has-override'); pop.remove(); }; pop.querySelector('[data-act=close]').onclick = () => pop.remove();
    pop.querySelector('[data-act=say]').onclick = async () => { try { const v = await import(this.base + 'voice-lab/js/voice.js'); const respell = pop.querySelector('[data-k=respell]').value.trim(); const text = respell && this.lingo ? this.lingo.toSpeech(word) : word; await v.say(respell ? `[[${(await import(this.base + 'lingo/js/lingo.js')).respellToEspeak(respell)}]]` : text, { engine: 'formant', pitch: 0.5 }); } catch (e) { console.warn(e); } };
    document.body.append(pop); }
  mountSettings(container, { onToggle = null } = {}) { const box = document.createElement('div'); box.className = 'langdbg-settings'; box.innerHTML = `<label><input type="checkbox" ${this.enabled ? 'checked' : ''}> Language debug (click words in spoken lines)</label> <button class="small" data-act="export">Export overrides</button> <button class="small" data-act="import">Import</button> <button class="small" data-act="submit">Submit to server</button> <span class="tiny" data-role="count">${Object.keys(this.overrides).length} overrides</span>`; box.querySelector('input').onchange = e => { this.enabled = e.target.checked; onToggle?.(this.enabled); }; box.querySelector('[data-act=export]').onclick = () => { const a = document.createElement('a'); a.href = 'data:application/json,' + encodeURIComponent(this.exportJSON()); a.download = 'lang-overrides.json'; a.click(); }; box.querySelector('[data-act=import]').onclick = () => { const i = document.createElement('input'); i.type = 'file'; i.accept = '.json'; i.onchange = async () => { const f = i.files[0]; if (f) { this.importJSON(await f.text()); box.querySelector('[data-role=count]').textContent = Object.keys(this.overrides).length + ' overrides'; } }; i.click(); }; box.querySelector('[data-act=submit]').onclick = async () => { const ok = await this.submit().catch(() => false); box.querySelector('[data-role=count]').textContent = ok ? 'sent to the server inbox' : 'server not reachable (use Export)'; }; container.append(box); return box; }
}
export const LANGDEBUG_CSS = `.langdbg-word{cursor:pointer;border-bottom:1px dotted #8a8;}.langdbg-word:hover{background:#3a4a3a}.langdbg-word.has-override{border-bottom:2px solid #e08a2a}.langdbg-pop{position:absolute;z-index:50;background:#1d1820;color:#eee;border:1px solid #555;border-radius:8px;padding:10px;width:330px;font-size:13px;box-shadow:0 6px 20px rgba(0,0,0,.5)}.langdbg-pop label{display:block;margin:6px 0}.langdbg-pop input{width:100%}.langdbg-pop .row{display:flex;gap:6px;margin-top:6px}.langdbg-settings{font-size:12px;display:flex;gap:6px;align-items:center;flex-wrap:wrap}`;
