#!/usr/bin/env python3
"""Write a block of <link rel="modulepreload"> tags into a page, one per ES module it will load.

    python3 tools/preload-modules.py prototypes/farhold/index.html
    python3 tools/preload-modules.py --check prototypes/farhold/index.html    # exit 1 if stale

Why (round 16): "The game takes a long time to load on my laptop over wifi. I can see each JS file
takes 2-5 seconds to load."

A browser cannot know a module exists until it has downloaded and parsed the module that imports it.
Farhold's graph is 190 modules and six levels deep, so a cold load is six serialized rounds of
fetching — and on wifi each round costs a lot more than it does on a wire. `modulepreload` is the
standard answer: the tags are in the HTML, so the browser starts all 190 at once, in parallel, with
the highest priority, and by the time `main.js` asks for a module it is already in the cache.

This is generated rather than hand-written because the import graph changes every time a module is
added, and a preload list that has drifted is worse than none (it fetches files nothing wants). The
block is delimited so re-running replaces it in place; `--check` is for the test suite.

It rewrites `three` and `three/addons/` through the page's own import map, so the hrefs it writes
are the URLs the browser will actually request.
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = '<!-- BEGIN modulepreload (generated by tools/preload-modules.py — do not edit by hand) -->'
END = '<!-- END modulepreload -->'

IMPORT_RE = re.compile(
    r"""(?:^|[\s;}])(?:import|export)\s[^'"()]*?from\s*['"]([^'"]+)['"]"""
    r"""|(?:^|[\s;}])import\s*['"]([^'"]+)['"]"""
    r"""|\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)""",
    re.M)


def read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()


def import_map(html):
    m = re.search(r'<script[^>]*type=["\']importmap["\'][^>]*>(.*?)</script>', html, re.S)
    if not m:
        return {}
    import json
    try:
        return json.loads(m.group(1)).get('imports', {})
    except Exception:
        return {}


def resolve(spec, from_file, imports, page_dir):
    """A bare specifier goes through the import map; a relative one is relative to its importer."""
    if spec.startswith('.') or spec.startswith('/'):
        return os.path.normpath(os.path.join(os.path.dirname(from_file), spec))
    for prefix, target in sorted(imports.items(), key=lambda kv: -len(kv[0])):
        if prefix.endswith('/') and spec.startswith(prefix):
            return os.path.normpath(os.path.join(page_dir, target + spec[len(prefix):]))
        if spec == prefix:
            return os.path.normpath(os.path.join(page_dir, target))
    return None


def walk(entries, imports, page_dir):
    """Breadth-first so the list comes out roughly in the order the browser would have wanted it."""
    seen, order, queue = set(), [], list(entries)
    while queue:
        path = queue.pop(0)
        path = os.path.normpath(path)
        if path in seen:
            continue
        seen.add(path)
        if not os.path.isfile(path):
            continue
        order.append(path)
        try:
            src = read(path)
        except Exception:
            continue
        # Comments can hold example import lines. Strip block comments before scanning so a doc
        # header that shows `import { x } from './nowhere.js'` does not add a 404 to every load.
        src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
        src = re.sub(r'^\s*//.*$', '', src, flags=re.M)
        for m in IMPORT_RE.finditer(src):
            spec = m.group(1) or m.group(2) or m.group(3)
            if not spec:
                continue
            target = resolve(spec, path, imports, page_dir)
            if target and target not in seen:
                queue.append(target)
    return order


def block_for(page):
    page = os.path.abspath(page)
    page_dir = os.path.dirname(page)
    html = read(page)
    imports = import_map(html)

    entries = []
    for m in re.finditer(r'<script[^>]*type=["\']module["\'][^>]*\ssrc=["\']([^"\']+)["\']', html):
        entries.append(os.path.normpath(os.path.join(page_dir, m.group(1))))
    if not entries:
        return None, html, []

    mods = walk(entries, imports, page_dir)
    # The entry scripts are already in the HTML as <script src>; preloading them again is noise.
    mods = [m for m in mods if m not in entries]
    # `modulepreload` says "this is a JavaScript module". A `await import('./x.json', {with:…})`
    # or a stray relative specifier that resolves to data is NOT one, and the browser refuses it
    # with "Expected a JavaScript-or-Wasm module script but the server responded with a MIME type
    # of application/json" — a console error on every load, which is enough to fail any test that
    # asserts a clean console. Preloading data files buys nothing anyway: they are fetched by
    # `fetch()`, not by the module loader.
    mods = [m for m in mods if os.path.splitext(m)[1].lower() in ('.js', '.mjs')]

    lines = [BEGIN,
             '<!-- %d modules, so the browser fetches them all at once instead of discovering them'
             ' six imports deep. Regenerate: python3 tools/preload-modules.py %s -->'
             % (len(mods), os.path.relpath(page, ROOT))]
    for m in mods:
        href = os.path.relpath(m, page_dir).replace(os.sep, '/')
        lines.append('<link rel="modulepreload" href="%s">' % href)
    lines.append(END)
    return '\n'.join(lines), html, mods


def splice(html, block):
    if BEGIN in html and END in html:
        start = html.index(BEGIN)
        end = html.index(END) + len(END)
        return html[:start] + block + html[end:]
    # First run: put it just before </head> so the tags are seen before any script runs.
    i = html.lower().rindex('</head>')
    return html[:i] + block + '\n' + html[i:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('pages', nargs='+')
    ap.add_argument('--check', action='store_true', help='exit 1 if any page is out of date')
    args = ap.parse_args()

    stale = False
    for page in args.pages:
        p = page if os.path.isabs(page) else os.path.join(ROOT, page)
        block, html, mods = block_for(p)
        if block is None:
            print('%s: no <script type="module" src> — nothing to preload' % page)
            continue
        out = splice(html, block)
        if out == html:
            print('%s: up to date (%d modules)' % (page, len(mods)))
            continue
        stale = True
        if args.check:
            print('%s: OUT OF DATE — run tools/preload-modules.py' % page)
            continue
        with open(p, 'w', encoding='utf-8') as f:
            f.write(out)
        print('%s: wrote %d modulepreload tags' % (page, len(mods)))
    sys.exit(1 if (stale and args.check) else 0)


if __name__ == '__main__':
    main()
